### ISSUE TITLE
PKG_MIRROR_HASH

### ISSUE THREAD

**Issue by 809205580** [liudf0716/apfree_wifidog#105]
I executing the command: sha256sum dl/apfree_wifidog-2.03.1061-2.03.1061.tar.gz, then obtain PKG_MIRROR_HASH=dc1a052bd61c1224dda9548475c1feda9332c40fc2190ca6e4901d432379b51c,
but the PKG_MIRROR_HASH in the Makefile is:40293b58d4be4ade84dc826a4a01c30a8ba97198c8040b0062fa8db0f8379987

**Comment by liudf0716** [comment]
@809205580 wifidog's package Makefile is just a demo for user's convenience.
