### ISSUE TITLE
libevent2

### ISSUE THREAD

**Issue by KazukiShimada** [liudf0716/apfree_wifidog#127]
Hi, Liu.

diizzyy is waiting for your opinion.
https://github.com/lede-project/source/pull/848#issuecomment-300411697

**Comment by liudf0716** [comment]
@KazukiShimada thanks for your reminder， I have answered that [question](https://github.com/lede-project/source/pull/1080).

**Comment by KazukiShimada** [comment]
Thanks, Liu.
