### ISSUE TITLE
访客与wifi断开连接后，wifidog还一直在向服务器上报

### ISSUE THREAD

**Issue by heartache1987** [liudf0716/apfree_wifidog#13]
1、访客连接wifi通过认证在服务器端上线；
2、访客断开与wifi的连接；
3、wifidog依然在向服务器上报，访客一直未下线。
![qq 20161206142648](https://cloud.githubusercontent.com/assets/24308203/20915308/12b6b2fc-bbc0-11e6-8a2e-b3a7756a3a72.png)

**Comment by KerwinKoo** [comment]
这个BUG提的好~!

**Comment by gigibox** [comment]
wifidog检测用户下线的机制不是实时的，流程就是这么设计的，不算bug

**Comment by liudf0716** [comment]
这个跟wifidog的统计流量有关，从后台数据看，的确有流量，这个需要改进一下
