### ISSUE TITLE
v2.05.1326 is stable?

### ISSUE THREAD

**Issue by KazukiShimada** [liudf0716/apfree_wifidog#130]
Hi, Liu.

Unfotunately I can't read Chinese. So I can't understand v2.05.1326 description.
https://github.com/liudf0716/apfree_wifidog/releases/tag/2.05.1326
Is v2.05.1326 stable?

regards,

**Comment by liudf0716** [comment]
Hi KazukiShimada,

Compared with version 2.03.1061, v2.05.1326 is a pre-release version, after a round of testing, our test team found a few unimportant bugs. If u are demanding, you'd better wait a few days for our official version; if not mind,  u can try this version, and if you find any bug of this version, please let me know by [issues](https://github.com/liudf0716/apfree_wifidog/issues/new). thanks!

regard,

Dengfeng

**Comment by KazukiShimada** [comment]
Hi, Liu.

Thank you for your reply.
Ah, I see. I'll wait for new release.

Yes, If I find the issues, I'll report.

Thanks in advance.
