### ISSUE TITLE
ipset need any dependency ?

### ISSUE THREAD

**Issue by qianguozheng** [liudf0716/apfree_wifidog#131]
I copy ipset.c and ipset.h as a standalone program.
I need to create table by "ipset -N xxxx iphash"
But I cannot find where apfree_wifidog do that, where did it do that ?

**Comment by liudf0716** [comment]
the ipset file only provides add&del function, not provides create function.

**Comment by qianguozheng** [comment]
Yes. 
Where apfree_wifidog do the create part ?

**Comment by liudf0716** [comment]
please read the code.

**Comment by qianguozheng** [comment]
ipset_do_command("create " CHAIN_TRUSTED " hash:mac timeout 0 ");
	ipset_do_command("create " CHAIN_ROAM " hash:mac timeout 0 ");
	ipset_do_command("create " CHAIN_UNTRUSTED " hash:mac timeout 0 ");
	ipset_do_command("create " CHAIN_DOMAIN_TRUSTED " hash:ip ");
	ipset_do_command("create " CHAIN_INNER_DOMAIN_TRUSTED " hash:ip ");
	ipset_do_command("create " CHAIN_IPSET_TDOMAIN " hash:ip ");
