### ISSUE TITLE
编译并安装成功，但是运行提示：-ash: /usr/bin/wifidog: not found

### ISSUE THREAD

**Issue by kukudemajia** [liudf0716/apfree_wifidog#132]
root@OpenWrt:/tmp# opkg install apfree_wifidog_2.03.1061-1_x86_64.ipk
Installing apfree_wifidog (2.03.1061-1) to root...
Configuring apfree_wifidog.
uci: Entry not found
root@OpenWrt:/tmp# /usr/bin/wifidog
-ash: /usr/bin/wifidog: not found

请问是什么问题呢？
OpenWrt Chaos Calmer 15.05.1 / LuCI 15.05-149-g0d8bbd2 Release (git-15.363.78009-956be55)

**Comment by liudf0716** [comment]
are u sure u compile apfree wifidog successly?

**Comment by kukudemajia** [comment]
编译成功，没有出错提示
今天又更新了一下lede的代码
这次编译也成功了，终于运行没问题了

**Comment by liudf0716** [comment]
good
