### ISSUE TITLE
Install apfree_wifidog on dd-wrt router

### ISSUE THREAD

**Issue by paradigmist** [liudf0716/apfree_wifidog#149]
Hi, I am looking for a way to install apfree_wifidog on dd-wrt device, is there any manual for this?
Thanks in advance.

**Comment by liudf0716** [comment]
sorry, we did not install apfree_wifidog on dd-wrt before. so we can not provide any help for that.
cause apfree_wifidog need many built-in package in openwrt&lede, such as libuci, ipset, dnsmasq,fping etc,
I dont know whether dd-wrt provide such package or not.

**Comment by paradigmist** [comment]
@liudf0716 Thanks for reply, I will look into openwrt.
