### ISSUE TITLE
make package/apfree_wifidog/compile V=s error with openwrt 15

### ISSUE THREAD

**Issue by mrsantran** [liudf0716/apfree_wifidog#153]
![screen shot 2017-06-24 at 7 16 42 am](https://user-images.githubusercontent.com/21286108/27504013-3e89194e-58ad-11e7-9600-b618c372b6db.png)

When i build apfree_wifidog on centos with openwrt 15.
Have error.
How to resolved ?

**Comment by liudf0716** [comment]
Need more information

**Comment by KazukiShimada** [comment]
You failed to build toolchain. You didn't even reach wifidog compile yet.
Try lede buildroot.
https://github.com/lede-project/source

**Comment by mrsantran** [comment]
I'm do all step in guide for  openwrt  and lede.

>https://github.com/liudf0716/apfree_wifidog/wiki/%E5%9F%BA%E4%BA%8ELEDE%E7%BC%96%E8%AF%91Apfree_wifidog

> https://github.com/liudf0716/apfree_wifidog/issues/86

try:
make package/apfree_wifidog/compile V=s
make package/apfree_wifidog/compile -j1 V=s
make package/apfree_wifidog/compile -j2 V=s
make package/apfree_wifidog/compile -j3 V=s
make package/apfree_wifidog/compile -j4 V=s
make V=s
...

but error at all.
video:
https://www.facebook.com/santran.686/videos/242151116271660/

**Comment by liudf0716** [comment]
KazukiShimada are right, before compile apfree wifidog, u should have toolchain built, in order to do that, u firstly should `make V=s` before compile apfree wifidog.

**Comment by mrsantran** [comment]
Thanks.

But run make V=s same error toolchain

**Comment by liudf0716** [comment]
that's LEDE&OPENWRT's problem, u can read their document to solve it.

**Comment by lcyenter** [comment]
Linking C executable wifidog
CMakeFiles/wifidog.dir/wd_util.c.o: In function `wd_gethostbyname':
wd_util.c:(.text+0x2804): warning: gethostbyname is obsolescent, use getnameinfo() instead.
/home/lcy/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libuci.so: warning: the use of `mktemp' is dangerous, better use `mkstemp'
CMakeFiles/wifidog.dir/simple_http.c.o: In function `evhttps_request':
simple_http.c:(.text+0x10c4): undefined reference to `bufferevent_openssl_set_allow_dirty_shutdown'
simple_http.c:(.text+0x10e0): undefined reference to `evhttp_connection_base_bufferevent_new'
CMakeFiles/wifidog.dir/https_server.c.o: In function `thread_https_server':
https_server.c:(.text+0x9bc): undefined reference to `evhttp_set_bevcb'
collect2: error: ld returned 1 exit status
make[5]: *** [src/wifidog] Error 1
make[5]: Leaving directory `/home/lcy/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/apfree_wifidog/apfree_wifidog-2.03.1061'
make[4]: *** [src/CMakeFiles/wifidog.dir/all] Error 2
make[4]: Leaving directory `/home/lcy/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/apfree_wifidog/apfree_wifidog-2.03.1061'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/lcy/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/apfree_wifidog/apfree_wifidog-2.03.1061'
make[2]: *** [/home/lcy/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/apfree_wifidog/apfree_wifidog-2.03.1061/.built] Error 2
make[2]: Leaving directory `/home/lcy/openwrt/package/apfree_wifidog'
make[1]: *** [package/apfree_wifidog/compile] Error 2
make[1]: Leaving directory `/home/lcy/openwrt'
make: *** [package/apfree_wifidog/compile] Error 2

I searched this problem a long time but can't find any solutions,how to solve this problem??

**Comment by liudf0716** [comment]
@lcyenter read this issue
https://github.com/liudf0716/apfree_wifidog/issues/138

**Comment by KazukiShimada** [comment]
Hi.
First of all, you should read README on top page.
https://github.com/liudf0716/apfree_wifidog

**Comment by lcyenter** [comment]
My god..I finally knew it,I don't need the https,I think it's not necessary,so it causes me failed many times..Thanks a lot!!!
