### ISSUE TITLE
Error: We did not get a valid answer from the central server

### ISSUE THREAD

**Issue by zainbouziane** [liudf0716/apfree_wifidog#155]
Hi,

Wifidog returns a page with the error: `Error: We did not get a valid answer from the central server`
While my auth server correctly returns: `Auth: 1` as i see in the webserver logs

What can be the problem?

**Comment by liudf0716** [comment]
please read this article
https://github.com/liudf0716/apfree_wifidog/wiki/apfree-wifidog%E8%AE%A4%E8%AF%81%E8%BF%94%E5%9B%9E-We-did-not-get-a-valid-answer-from-the-central-server

**Comment by zainbouziane** [comment]
My /auth file contains this: 
`<?PHP
echo "Auth: 1";`

But i still get the same error `Error: We did not get a valid answer from the central server`

**Comment by liudf0716** [comment]
u can debug apfree wifidog like this
wifidog -c /tmp/wifidog.conf -f -d 7

**Comment by zainbouziane** [comment]
Thanks, found the error. My server was returning a 301 error due to a rule in my .htaccess
