### ISSUE TITLE
Domain block feature?

### ISSUE THREAD

**Issue by zainbouziane** [liudf0716/apfree_wifidog#157]
Hi,

A suggestion for a new feature:
The possibility to blacklist certain domains, so that they cannot be accessed anytime.

**Comment by liudf0716** [comment]
it seems gateway system's feature

**Comment by KazukiShimada** [comment]
Try https://github.com/openwrt/packages/tree/master/net/simple-adblock
Or https://github.com/openwrt/packages/tree/master/net/adblock
