### ISSUE TITLE
Can't not Capture Https.

### ISSUE THREAD

**Issue by LeonKendy** [liudf0716/apfree_wifidog#161]
Hi,
When i access https by mobile phone running os android.I don't see capture HTTPS URL request.Example : google, and facebook.....
![19820927_854645571355353_1410145745_o](https://user-images.githubusercontent.com/29971254/27945844-0c4f7b1e-6319-11e7-9a55-5e13ac1cbb10.png)

**Comment by liudf0716** [comment]
@LeonKendy In fact, from your pic, apfree has captured https request.

**Comment by LeonKendy** [comment]
@liudf0716 
I mean it's not redirect to page login to access internet .

**Comment by liudf0716** [comment]
@LeonKendy  I know what u mean, but https can not hijack like http, that why it's https. https client must notify user when it found  web's cert is illegal, of course, apfree use illegal cert for https client.

**Comment by LeonKendy** [comment]
hi @liudf0716 ,
thank you for your answer and i have one more question.
How to show Capture when case user accept https for them login active internet.
Because am my laptop when accept https it will show one more tab login for user login but my phone it not.

**Comment by rahacker2006** [comment]
@LeonKendy you resolve the issue? please confirm

**Comment by rahacker2006** [comment]
And how did you do it? @LeonKendy
