### ISSUE TITLE
Update Apfree_wifidog-v2.06.1395 start error Segmentation fault.

### ISSUE THREAD

**Issue by LeonKendy** [liudf0716/apfree_wifidog#164]
I installed apfree_wifidog ver latest releases complete. Then I run the command /etc/init.d/wifidog start and ps | Grep wifidog. And I detected the wifidog process not active. I checked the system logs apart from the web interface, the following message was detected.
I removed the installation of Apfree_wifidog ver latest releases and reinstalled Apfree_wifidog ver 2.03.1061. Then run the command /etc/init.d/wifidog start and ps | Grep wifidog sees active wifidog process
Look forward to somebody's help :(
![ap5](https://user-images.githubusercontent.com/29971254/27984603-43e04d7e-6404-11e7-9c80-97c9e92fbbc3.png)
![ap4](https://user-images.githubusercontent.com/29971254/27984605-48316bb0-6404-11e7-8cea-5ddd93fd4aa7.png)
![ap6](https://user-images.githubusercontent.com/29971254/27984606-4fbab59e-6404-11e7-8d75-e8de7e1f7c56.png)

**Comment by LeonKendy** [comment]
I check command /usr/bin/wifidog -c /tmp/wifidog.conf -f -d 0 and i recived message faild Ip Tables .
![ap7](https://user-images.githubusercontent.com/29971254/27987985-af52b258-6441-11e7-89bf-2d422ae9768b.png)
![ap8](https://user-images.githubusercontent.com/29971254/27987986-af61d74c-6441-11e7-8023-6b8839d340b1.png)

**Comment by LeonKendy** [comment]
I check command /usr/bin/wifidog -c /tmp/wifidog.conf -f -d 10 and i recived message ip tables command faild 
![a8](https://user-images.githubusercontent.com/29971254/27988103-2b600826-6444-11e7-851a-a90dfca79e1a.png)
![a9](https://user-images.githubusercontent.com/29971254/27988104-2b67d61e-6444-11e7-96d6-213948bf3fef.png)

**Comment by liudf0716** [comment]
when wifidog start, it will initialize iptables rules : flush and delete possible wifidog rule, if it firstly start, wifidog rule does not exist, so u can see many info about iptables execute failed. it's not problem.
