### ISSUE TITLE
Authentication server check bug.

### ISSUE THREAD

**Issue by xzfth16** [liudf0716/apfree_wifidog#166]
When I build the authentication server on the X86 router(Meaning the router itself is the authentication server), apfree_wifidog can not be able to detect server bug。
error log:
[6][Mon Jul 31 21:38:49 2017][30953](centralserver.c:412) Sorry, internet is not available!
[3][Mon Jul 31 21:38:49 2017][30953](centralserver.c:329) Failed to connect to any of the auth servers
http error page display:
"Error!", "Error: We did not get a valid answer from the central server"

PS:Original wifidog no such error.

**Comment by liudf0716** [comment]
when apfree wifidog connect auth server, it will detect whether the device is online or not, if not, it will not connect auth server.

**Comment by xzfth16** [comment]
if auth server = itself ， can not detect itself ！wifidog no such problem，apfree_wifidog has this problem。

**Comment by xzfth16** [comment]
You can try it yourself，I have tested many times。

**Comment by liudf0716** [comment]
your device is online?

**Comment by xzfth16** [comment]
Suer!Correct access to the Internet.
