### ISSUE TITLE
missing file mosquitto.h

### ISSUE THREAD

**Issue by etmad8** [liudf0716/apfree_wifidog#167]
/build_dir/target-mips_24kc_musl/apfree_wifidog/apfree_wifidog-2.03.1061/src/mqtt_thread.c:36:23: fatal error: mosquitto.h: No such file or directory

missing file

**Comment by liudf0716** [comment]
please compile mosquitto firstly

**Comment by serezhka** [comment]
Same here.

@liudf0716 , could you please explain where and how mosquitto.h have to be placed? 
libmosquitto-dev & mosquitto-dev are installed

-- 
There are other build errors, for example 
http://downloads.openwrt.org/sources/linux-firmware-2016-01-25-52442afee9907bc32a058f22bb3295d040677c26.tar.xz isn't available .. 
It can be downloaded from http://dev.gateworks.com/sources/
and placed in [openwrt]/dl/

**Comment by liudf0716** [comment]
@serezhka u need to compile mosquitto, not just install it
make package/mosquitto/compile V=s

**Comment by zcfrank1st** [comment]
After `make package/mosquitto/compile V=s`, compiling apfree_wifidog is still error :
Package apfree_wifidog is missing dependencies for the following libraries:
libmosquitto.so.1...

**Comment by liudf0716** [comment]
@zcfrank1st  do u choose libmosquitto?
make menuconfig ---> choose libmosquitto

**Comment by zcfrank1st** [comment]
done,  thanks

**Comment by stevetao74** [comment]
@nuwanarti it's suiting to apt install, good ¡
