### ISSUE TITLE
I want install apfree_wifidog to openwrt(Linux version 3.3.8).

### ISSUE THREAD

**Issue by Tianxiaomo** [liudf0716/apfree_wifidog#189]
Now,we use wifidog-1.3, but it have a lot of problems.Such as, the ad cannot jump out, open too slowly.So,I   
want use apfree-wifidog, however, always to expect problems when I build  source code.Feel terrible.

**Comment by liudf0716** [comment]
@Tianxiaomo  how about try compile in this sdk environment:
https://github.com/KunTengRom/kunteng-lede-17.01.4
