### ISSUE TITLE
maybe keep-alive can't guarantee request get right reponse?

### ISSUE THREAD

**Issue by fenggui321** [liudf0716/apfree_wifidog#191]
apfree_wifidog change HTTP1.0 to HTTP1.0 and support keep-alive.My question is : How apfree_wifidog assure the reponse corresponding  to exactly orignal request? .e.g.:apfree_wifidog thread A B trigger  Request A B,both on the same socket context ("Use keep-alive http connection"), and both thread call recv to get respnse,how to gurantee thread A---request A get reponse A ,not response B ?

**Comment by liudf0716** [comment]
@fenggui321 yes, I thought what u  decription is reasonable, I cann't promise thread A's request get thread A's response, I will concel keep-alive feature before finding proper solution. thanks!

**Comment by liudf0716** [comment]
@fenggui321 did u have wechat?

**Comment by fenggui321** [comment]
@liudf0716 for what ?
