### ISSUE TITLE
problem when ip host change sever not ping or auth token to sever.

### ISSUE THREAD

**Issue by tidus30691nexus5** [liudf0716/apfree_wifidog#199]
Am using last version.
Host using sevice cloudflare.

When first all runnning ok and ip auth sever is: 104.22.6.100 . But when host sever ( use cloudflare ) change ip router not ping or auth to my sever . After am restart wifidog it work again and am seen ip auth sever change (104.22.5.100)

am think have problem on function _connect_auth_server 

please help me check problem

**Comment by liudf0716** [comment]
@tidus30691nexus5 next release we will fix this problem.

**Comment by tidus30691nexus5** [comment]
am think problem is firewall not add new ip when host server auth change new ip. 
because wifidog till running. am can use wdctl status to see client online and active

**Comment by liudf0716** [comment]
yes, wdctl status can get what u want.

**Comment by tidus30691nexus5** [comment]
hi @liudf0716 ,
Am add more config **list firewall_rule_global	'allow to 104.22.0.0/22**' and run again,
After run 6hour wifidog not ping or auth to sever auth again.
But am check wdctl status it till running on router. So when unknow user connect wifi can't show page captive for user login.
Please help me fix it. Thanks

**Comment by tidus30691nexus5** [comment]
@liudf0716 
problem is when ip change it mark server down and never recheck again .
