### ISSUE TITLE
apfree_wifidog UCI 与原生wifidog参数支持不全

### ISSUE THREAD

**Issue by springLee1989** [liudf0716/apfree_wifidog#205]
AuthServer {
	LoginScriptPathFragment 
	PortalScriptPathFragment 
	MsgScriptPathFragment 
	PingScriptPathFragment 
	AuthScriptPathFragment 
}
以上参数无法配置

**Comment by liudf0716** [comment]
修改一下init.d中的wifidog脚本就可以了。可以提个pr，谢谢！
