### ISSUE TITLE
2.10.1437更新说明有提到有线免认证？

### ISSUE THREAD

**Issue by xzfth16** [liudf0716/apfree_wifidog#206]
在看2.10.1437更新说明，有有线免认证功能？请问如何使用

**Comment by liudf0716** [comment]
u need set wired_passed as 1 to turn on feature of wired device passing through auth, please refered this file ：
https://github.com/KunTengRom/kunteng-lede-17.01.4/blob/17.01.4/package/kunteng/net/apfree_wifidog/files/wifidog.conf
good luck！
