### ISSUE TITLE
<html><body>Please <a href='%s'>click here</a>.</body></html>

### ISSUE THREAD

**Issue by xzfth16** [liudf0716/apfree_wifidog#207]
有的手机出现这样的页面 是什么问题？错误代码307

**Comment by xzfth16** [comment]
v2.10.1437 release

**Comment by xzfth16** [comment]
出现该页面的时候虽然显示Please  click here，但实际无法点击或者叫点击无反应

**Comment by liudf0716** [comment]
how to reproduce that? can u give more clue? thx

**Comment by xzfth16** [comment]
出问题的是这部手机，每次都出现
![mmexport1527390889704](https://user-images.githubusercontent.com/29062929/40582172-da5bf7e6-619f-11e8-8d19-fdd74cd9f79c.jpg)

**Comment by liudf0716** [comment]
which browser？maybe it's browser's problem.

**Comment by xzfth16** [comment]
用的安卓系统默认的浏览器
