### ISSUE TITLE
install apfree_wifidog

### ISSUE THREAD

**Issue by medrockstar** [liudf0716/apfree_wifidog#208]
Hi,

How to install apfree_wifidog in OpenWrt ?

I'm Newbie.

Tks,

**Comment by liudf0716** [comment]
@medrockstar u can try this sdk
https://github.com/KunTengRom/kunteng-lede-17.01.4
apfree wifidog was integrated in that sdk

**Comment by medrockstar** [comment]
Can I install apfree_wifidog in my access point TP-link ?

**Comment by liudf0716** [comment]
if your tp-link support openwrt&lede, of couse u can install

**Comment by medrockstar** [comment]
you have a package that I will install with opkg install ?

**Comment by liudf0716** [comment]
I have submit apfree wifidog to openwrt package, unfortunately not accepted.
so u can not install it with 'opkg install' method
