### ISSUE TITLE
在http://openwrt.kunteng.org/sources下载一直失败，报超时

### ISSUE THREAD

**Issue by aoliaopaopao** [liudf0716/apfree_wifidog#209]
SHELL= flock /root/lede/tmp/.compat-wireless-2017-01-31.tar.xz.flock -c '  	/root/lede/scripts/download.pl "/root/lede/dl" "compat-wireless-2017-01-31.tar.xz" "75e6d39e34cf156212a2509172a4a62b673b69eb4a1d9aaa565f7fa719fa2317" "" "http://openwrt.kunteng.org/sources"    '

**Comment by liudf0716** [comment]
fixed! pls try it again. thanks for your repoart
