### ISSUE TITLE
make过程中 /usr/bin/ld: cannot find -liptext ??

### ISSUE THREAD

**Issue by net5** [liudf0716/apfree_wifidog#212]
[ 89%] Linking C executable wifidog
/usr/bin/ld: cannot find -liptext
/usr/bin/ld: cannot find -liptext4
collect2: error: ld returned 1 exit status
make[2]: *** [src/wifidog] Error 1
make[1]: *** [src/CMakeFiles/wifidog.dir/all] Error 2
make: *** [all] Error 2

**Comment by liudf0716** [comment]
u'd better use the following sdk environment to compile apfree wifidog, which include all depends package
https://github.com/KunTengRom/kunteng-lede-17.01.4
