### ISSUE TITLE
Eventually am able to access the internet (without being authenticated)

### ISSUE THREAD

**Issue by bilalk1** [liudf0716/apfree_wifidog#215]
Hey guys,

Basically, I'm using this Wifidog for the splash page.
it's working fine.
Connect my Device to wifi go to the splash page and after submitting page got internet access.
But when I am using an iPhone if I connect and disconnect repeatedly without passing the caprice portal, I eventually am able to access the internet (without being authenticated). I usually need to do this connect/disconnect cycle a few dozen times.

**Comment by liudf0716** [comment]
@bilalk1 for iphone device, when it connect wifi, it will send many captive.apple.com http request, if the device didn't receive OK response, it will show splash page; however, if the device constantly did'nt receive Ok response, it  will disconnect the wifi; for this reason, if apfree wifidog find the device is iphone device, apfree will not send OK response firstly, but after receive 'captive.apple.com' request for more than 20 seconds, it will temporary pass the device for 1 minutes, that's what u found
