### ISSUE TITLE
Compile error on Ubuntu 

### ISSUE THREAD

**Issue by duydeja-vu** [liudf0716/apfree_wifidog#218]
![compile_error](https://user-images.githubusercontent.com/34203267/50411427-84bee200-0832-11e9-95cc-dc4b2b3e0103.png)
I try compile Apfree-wifidog on Ubuntu, target system is BCM27xx ( Raspberry pi3 model B). 
I can't solve the problem. 
Thanks everyone !!

**Comment by duydeja-vu** [comment]
Relation with your mother bitch !!!

**Comment by liudf0716** [comment]
@duydeja-vu fuck your mother, if u want to fuck. your sb
