### ISSUE TITLE
How to write log to OpenWRT syslog?

### ISSUE THREAD

**Issue by khoailangdo** [liudf0716/apfree_wifidog#222]
I changed like this:
`debugconf_t debugconf = {
    .debuglevel = LOG_WARNING,
    .log_stderr = 1,
    .log_syslog = 1,
    .syslog_facility = 1
};
`
But I still don't see the log in OpenWRT syslog.
What happened? Please help me!

**Comment by liudf0716** [comment]
try `logread` to see whether it appeared or not
