### ISSUE TITLE
enable apfree_wifidog

### ISSUE THREAD

**Issue by hanis94** [liudf0716/apfree_wifidog#225]
hi,
This ismy config file 
config wifidog
	option gateway_interface 'br-lan'
	option auth_server_hostname 'wifidog.kunteng.org.cn'
	option auth_server_port 443
	option auth_server_path '/wifidog/'
	option check_interval 60
	option client_timeout 5
	option wired_passed 0
	option disabled 0
but when I try to start with the command
service wifidogx start is show me 
wifidogx disabled in /etc/config/wifidogx file, please set disabled to 0 to enable it
no wifidogx.conf, exit...

I try it with my auth_server_hostname is the same problem 
how can I fix it ?
thanks

**Comment by liudf0716** [comment]
after set disabled to 0, then /etc/init.d/wifidogx start
