### ISSUE TITLE
url编码bug

### ISSUE THREAD

**Issue by wilinz** [liudf0716/apfree_wifidog#234]
调试ping接口
GET

http://localhost:8001/wifidog/ping?gw_id=ABCDEF112233&sys_uptime=1000&sys_memfree=10&sys_load=0.23&nf_conntrack_count=100&cpu_usage=32%&wifidog_uptime=100&online_clients=2&offline_clients=1&ssid=apfree&version=1.23&channel_path=wificoin&wired_passed=0

cpu_usage=32% 中的%没有使用url编码成%25，导致服务器解析异常

**Comment by liudf0716** [comment]
@wilinz fixed
