### ISSUE TITLE
认证端数组取值问题

### ISSUE THREAD

**Issue by geyoulei** [liudf0716/apfree_wifidog#25]
数组
$arr=array('route_id'=>1,'shop_id'=>2);
$route_id = $arr['route_id'];
echo $route_id;
在安卓认证弹窗取值正常,安卓浏览器取值正常.
苹果手机浏览器取值正常,但是在弹窗取不到值有问题。求解决办法

**Comment by liudf0716** [comment]
看不出这个跟apfree wifidog之间有什么关联啊？属于服务器端的问题。

**Comment by geyoulei** [comment]
我刷过原版的wifidog认证端是没有问题的。苹果弹出的窗口认证正常。不过原版wifidog不稳定。谢谢了

**Comment by liudf0716** [comment]
apfree wifidog针对苹果弹窗做了相应的处理，如果安装原版的wifidog处理流程，会导致ios弹窗后断开网络连接， 你提的问题有可能是因为js_filter打开的原因导致的，可以把js_filter关闭试试看。

**Comment by geyoulei** [comment]
如何关闭 js_filter。

**Comment by liudf0716** [comment]
在 /etc/config/wifidog文件中
添加 
option js_filter '0'

/etc/init.d/wifidog start

在/tmp/wifidog.conf文件中能找到 
JsFilter	0
证明生效
