### ISSUE TITLE
Using apfree on x86 

### ISSUE THREAD

**Issue by Tr4cer0ute** [liudf0716/apfree_wifidog#51]
Hi,

Did you try to run Apfree on x86 architecture? can it handel hotel traffic with 20 APs? What are the limitations

**Comment by liudf0716** [comment]
not yet tested. But I can promise that Apfree will not crash when encounting high load pressure. 
cause wifidog is based on mac and ip pair, I think it limited by network subnet. u can only and better define your subnet less than 250.

**Comment by Tr4cer0ute** [comment]
I will process fot a stress test then revert with results.

**Comment by liudf0716** [comment]
Ok. 
In fact, we have done stress test.  that's why I can promise.
