### ISSUE TITLE
Apfree stop working when I put trusted domains

### ISSUE THREAD

**Issue by Tr4cer0ute** [liudf0716/apfree_wifidog#57]
Hi,

Apfree stop working and connect people automatically when I set Facebook trusted domains

here my line

option trusted_domains 'facebook.com,fbcdn.net,facebook.net,web.facebook.com,akamaihd.net'

**Comment by liudf0716** [comment]
can u show me file '/tmp/wifidog.conf', that file was real used by apfree wifidog.
by the way, if u want user can access facebook, u can try pan domain, like this:
wdctl add_trusted_pdomains facebook.com,fbcdn.net,facebook.net,akamaihd.net
if u want to save what u added rules, u can use 
'wdctl user_cfg_save'

**Comment by Tr4cer0ute** [comment]
Walled garden is not working properly, FBCDN.net subdomain are blocked (can't get ressources)

**Comment by liudf0716** [comment]
@Tr4cer0ute u should use pan domains. I think u want all *.fbcdn.net be accessed. but trusted domain only resolve fbcdn.net's ip, which should not be what u want.

**Comment by Tr4cer0ute** [comment]
@liudf0716 That's it. I want to allow all sub domains. What is the option line under configuration file? is it 

> option trusted_pan_domains

**Comment by Tr4cer0ute** [comment]
@liudf0716 please point to the required option
