### ISSUE TITLE
Failed to build for MIPS architecture

### ISSUE THREAD

**Issue by Tr4cer0ute** [liudf0716/apfree_wifidog#60]
Hi, 

I'am trying to compile apfree for MIPS architecture but it won't success, knowing that I'm using the same build to compile ar71x and it working fine.

**Comment by Tr4cer0ute** [comment]
Here is the error

> Volumes/OpenWRT/openwrt-archer-c2/staging_dir/toolchain-mipsel_24kec+dsp_gcc-5.3.0_musl-1.1.14/lib/gcc/mipsel-openwrt-linux-musl/5.3.0/../../../../mipsel-openwrt-linux-musl/bin/ld: copy reloc against protected `__stack_chk_guard' is dangerous
> CMakeFiles/wifidog.dir/https_server.c.o: In function `serve_some_http':
> /Volumes/OpenWRT/openwrt-archer-c2/build_dir/target-mipsel_24kec+dsp_musl-1.1.14/apfree_wifidog/apfree_wifidog-1.12.797/src/https_server.c:313: undefined reference to `evhttp_set_bevcb'
> collect2: error: ld returned 1 exit status
>

**Comment by liudf0716** [comment]
u need use libevent2 2.1.8 version
