### ISSUE TITLE
请问auth_server_port端口不支持443 ,是我编译问题还是?

### ISSUE THREAD

**Issue by xunni1000** [liudf0716/apfree_wifidog#62]
路由固件版本:opnewrt CC 15.05.1
libopenssl版本: 1.0.2j
libevent2版本:release-2.1.8-stable

除了认证服务器不支持https外.

认证的时候在firefox 和 chrome中 HSTS的网站会报错. (比如https://www.google.com  貌似百度现在也启用hsts),只有忽略错误后才能弹出认证页面.

openwrt 有个[luci-app-koolproxy](https://github.com/openwrt-develop/luci-app-koolproxy) 过滤广告支持https的.
它安装运行后在地址栏输入110.110.110.110 会弹出根证书安装.
不知道通过类似的方法能不能解决HSTS网站报错的问题.

**Comment by liudf0716** [comment]
证书被认为不合法，做https劫持跳转没法解决这个报警问题。如果能解决的话，那就是TLS协议的bug了。
