### ISSUE TITLE
evhttp_request_get_connection need free

### ISSUE THREAD

**Issue by jickding** [liudf0716/apfree_wifidog#67]
/**
 * Returns the connection object associated with the request or NULL
 *
 * The user needs to either free the request explicitly or call
 * evhttp_send_reply_end().
 */
EVENT2_EXPORT_SYMBOL
struct evhttp_connection *evhttp_request_get_connection(struct evhttp_request *req);

**Comment by liudf0716** [comment]
thanks. Could u submit PR to fix that bug?

**Comment by Tr4cer0ute** [comment]
I got this error only while dealing with the new release, the old one if working fine.

**Comment by jickding** [comment]
ok !!! so easy.
