### ISSUE TITLE
通过mqtt接口无法删除ip白名单

### ISSUE THREAD

**Issue by heartache1987** [liudf0716/apfree_wifidog#78]
操作步骤：
1.添加一个IP白名单：10.1.1.144；
2.执行mqtt命令行删除IP白名单：mosquitto_pub -h wifidog.kunteng.org -p 1883 -t wifidog/D4EE07251D16/request/111 -m "{\"op\":\"del_trusted\",\"type\":\"ip\",\"value\":\"10.1.1.144\",\"time\":\"201704261817\"}
"
执行结果：
   IP白名单未删除。

**Comment by gigibox** [comment]
![](https://avatars0.githubusercontent.com/u/24308203?v=3&s=460)

**Comment by caizhibang** [comment]
fixed this bug.
