### ISSUE TITLE
error in package for luci apfree in openwrt 15.05.1

### ISSUE THREAD

**Issue by JJEU** [liudf0716/apfree_wifidog#85]
Hello,

I followed the instructions provided for building apfree_wifidog.
after I pulled the source for apfree_wifidog, i noticed a folder called "luci-app-apfree_wifidog"

I copied it also in the folder <openWRTbuildroot>/package

but when i did the make menuconfig, there was an error about luci-app-apfree_wifidog.
the log sais it cannot find luci.mk

I found an error in the file luci-app-apfree_wifidog\makefile

original
` include ../../luci.mk`

corrected 
`include ../../feeds/luci/luci.mk`

after this the make menuconfig is correct, the package luci-app-apfree_wifidog appears in the "LUCI" category

Sorry for not following the github functions for the pull requests, actually i am an admin not a dev so i don't know how it works really.

Oh also, you should talk about the luci-app-apfree_wifidog package in the README.md file

**Comment by liudf0716** [comment]
@JJEU could u please provide pull request to modify our README?
