### ISSUE TITLE
-m state --state

### ISSUE THREAD

**Issue by 809205580** [liudf0716/apfree_wifidog#88]
请使用-m conntrack --ctstate 替换 -m state --state
新版的LEDE里面的iptables默认已去掉state模块的支持。

**Comment by liudf0716** [comment]
@809205580 thanks, we will treat that problem asap

**Comment by liudf0716** [comment]
@809205580 by the way, if u have solution, please dont hesitate to provide your pull request to fix that problem.

**Comment by liudf0716** [comment]
thanks for your pr, please add your name to our contributor file.

https://github.com/liudf0716/apfree_wifidog/blob/master/contributors.md
