### ISSUE TITLE
alternative for hash:mac ?

### ISSUE THREAD

**Issue by odkrys** [liudf0716/apfree_wifidog#93]
I am trying to compile for asuswrt-merlin.
However, merlin firmware use old kernel so there is no module for hash:mac.

ip_set_bitmap_ip.c
ip_set_bitmap_ipmac.c
ip_set_bitmap_port.c
ip_set_core.c
ip_set_getport.c
ip_set_hash_ip.c
ip_set_hash_ipport.c
ip_set_hash_ipportip.c
ip_set_hash_ipportnet.c
ip_set_hash_net.c
ip_set_hash_netport.c
ip_set_list_set.c

there is any alternative to rewrite fw_iptables.c?

**Comment by liudf0716** [comment]
@odkrys in old linux kernel version,  ipset does not support hash:mac. so if  want use apfree wifidog, ipset's hash:mac related features can not be used, which include black&white mac features.
