### ISSUE TITLE
wdctl add_trusted_pdomains

### ISSUE THREAD

**Issue by Tr4cer0ute** [liudf0716/apfree_wifidog#95]
wdctl add_trusted_pdomains [domain1.com, domain2.com ] doesn't take any effect event if it display "Yes" output.

**Comment by liudf0716** [comment]
@Tr4cer0ute if reading code of apfree wifidog, u will find pan domains related features are aided by dnsmasq. so u should add dnsmasq-full version to your firmware. noticing must select "build with ipset support"

**Comment by Tr4cer0ute** [comment]
I already have it installed 

> Package dnsmasq (2.77test4-1) installed in root is up to date.

The thing is, once I add pad domains, the DHCP server stop working and I can no longer get an IP

**Comment by liudf0716** [comment]
@Tr4cer0ute we did not test that dnsmasq version, how about the output of this command:
dnsmasq -C /var/etc/dnsmasq.conf -d

**Comment by Tr4cer0ute** [comment]
dnsmasq: failed to create listening socket for port 53: Address in use

**Comment by liudf0716** [comment]
u should stop dnsmasq before running dnsmasq in debug mode
